const projectsData = [
  {
    src: "/conversor.png",
    title: "Cryptocurrency Converter",
    description: "A web application for converting various cryptocurrencies.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/react.png",
      "/tailwind.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://convertidor-criptomonedas2022.netlify.app",
    urlGithub: "https://github.com/JoelVR17/Conversor-de-Criptomonedas",
    urlGithub2: "",
  },
  {
    src: "/veterinary.png",
    title: "Veterinary Appointments",
    description: "An app designed to manage veterinary appointments.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/react.png",
      "/tailwind.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://veterinaria-pacientes2022.netlify.app",
    urlGithub: "https://github.com/JoelVR17/Citas-Veterinaria",
    urlGithub2: "",
  },
  {
    src: "/Expense Control.png",
    title: "Expense Control",
    description: "A web-based tool for managing expenses of any type.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/react.png",
      "/tailwind.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://control-de-gastos2022.netlify.app",
    urlGithub: "https://github.com/JoelVR17/Control-de-Presupuesto",
    urlGithub2: "",
  },
  {
    src: "/americanStore.png",
    title: "American Store",
    description:
      "An online application to manage the inventory of an American store.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/js.png",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/java/java-plain.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/spring/spring-original.svg",
    ],
    link: true,
    twoRepos: false,
    url: "https://app.marcoaraya.live",
    urlGithub: "https://github.com/coxmars/Moda-Americana-App",
    urlGithub2: "",
  },

  {
    src: "/food-kioks.png",
    title: "Food Kiosk",
    description:
      "An online application to manage the inventory of any store (In Building)",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/postgresql/postgresql-original.svg",
      "/react.png",
      "/tailwind.png",
      "/ts.png",
      "/next.png",
    ],
    link: false,
    twoRepos: false,
    url: "",
    urlGithub: "https://github.com/JoelVR17/Food-Kiosk",
    urlGithub2: "",
  },
  {
    src: "/hometask.png",
    title: "Home Task",
    description:
      "An online application to manage the projects with their taks. (us: admin, pwd: admin12345)",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/mongodb/mongodb-original.svg",
      "/react.png",
      "/tailwind.png",
      "/ts.png",
      "/node-js.png",
      "/express.png",
    ],
    link: true,
    twoRepos: true,
    url: "https://home-task-frontend.vercel.app",
    urlGithub: "https://github.com/JoelVR17/Home-Task-Frontend",
    urlGithub2: "https://github.com/JoelVR17/Home-Task-Backend",
  },
  {
    src: "/inBuilding.jpeg",
    title: "StockHub",
    description:
      "An online application to manage the inventory of any store (In Building)",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/csharp/csharp-original.svg",
      "/react.png",
      "/ts.png",
      "/tailwind.png",
      "https://raw.githubusercontent.com/devicons/devicon/6910f0503efdd315c8f9b858234310c06e04d9c0/icons/microsoftsqlserver/microsoftsqlserver-plain-wordmark.svg",
      "/Firebase.png",
    ],
    link: false,
    twoRepos: false,
    url: "",
    urlGithub: "https://github.com/JoelVR17/StockHub",
    urlGithub2: "",
  },
];

export default projectsData;
