const projectsData = [
  {
    src: "/conversor.png",
    title: "Cryptocurrency Converter",
    description: "A web application for converting various cryptocurrencies.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/react.png",
      "/tailwind.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://convertidor-criptomonedas2022.netlify.app",
    urlGithub: "https://github.com/JoelVR17/Conversor-de-Criptomonedas",
    urlGithub2: "",
  },
  {
    src: "/veterinary.png",
    title: "Veterinary Appointments",
    description: "An app designed to manage veterinary appointments.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/react.png",
      "/tailwind.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://veterinaria-pacientes2022.netlify.app",
    urlGithub: "https://github.com/JoelVR17/Citas-Veterinaria",
    urlGithub2: "",
  },
  {
    src: "/Expense Control.png",
    title: "Expense Control",
    description: "A web-based tool for managing expenses of any type.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/react.png",
      "/tailwind.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://control-de-gastos2022.netlify.app",
    urlGithub: "https://github.com/JoelVR17/Control-de-Presupuesto",
    urlGithub2: "",
  },
  {
    src: "/Line Drawing.png",
    title: "Line Drawing",
    description:
      "An application for creating and editing line drawings in live.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/js.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://dibujosenlinea.netlify.app",
    urlGithub: "https://github.com/JoelVR17/DibujosEnLinea",
    urlGithub2: "",
  },
  {
    src: "/pokedex.png",
    title: "Pokedex",
    description: "A digital Pokédex showcasing information about Pokémon.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/js.png",
    ],
    link: true,
    twoRepos: false,
    url: "https://pokedexjoel.netlify.app/index.html",
    urlGithub: "https://github.com/JoelVR17/App-Pokemon",
    urlGithub2: "",
  },
  {
    src: "/twitterClone.png",
    title: "Twitter Clone",
    description: "A simplified version of Twitter, replicating key features.",
    icons: ["/next.png", "/tailwind.png", "/ts.png", "/react.png"],
    link: false,
    twoRepos: false,
    url: "",
    urlGithub: "https://github.com/JoelVR17/twitter-clone",
    urlGithub2: "",
  },
  {
    src: "/manageBooks.png",
    title: "Manage Books",
    description: "A book management system. A basic CRUD with images.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/node-js.png",
      "/express.png",
    ],
    link: false,
    twoRepos: false,
    url: "",
    urlGithub: "https://github.com/JoelVR17/Manage-Books",
    urlGithub2: "",
  },
  {
    src: "/hometask.png",
    title: "Home Task",
    description: "An application designed to organize and manage home tasks.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "/tailwind.png",
      "/node-js.png",
      "/express.png",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/mongodb/mongodb-original.svg",
      "/react.png",
    ],
    link: false,
    twoRepos: true,
    url: "",
    urlGithub: "https://github.com/JoelVR17/HomeTask-Backend",
    urlGithub2: "https://github.com/JoelVR17/HomeTask-Frontend",
  },
  {
    src: "/favoriteVideos.png",
    title: "Favorite Videos",
    description:
      "A web tool for saving and managing favorite videos from Youtube.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/react.png",
    ],
    link: false,
    twoRepos: false,
    url: "",
    urlGithub: "https://github.com/JoelVR17/Favorite_Videos",
    urlGithub2: "",
  },
  {
    src: "/americanStore.png",
    title: "American Store",
    description:
      "An online application to manage the inventory of an American store.",
    icons: [
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/html5/html5-original.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/css3/css3-original.svg",
      "/js.png",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/java/java-plain.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/spring/spring-original.svg",
    ],
    link: true,
    twoRepos: false,
    url: "https://app.marcoaraya.live",
    urlGithub: "https://github.com/coxmars/Moda-Americana-App",
    urlGithub2: "",
  },
];

export default projectsData;
