const projectsData = [
  {
    src: "/conversor.png",
    title: "Cryptocurrency Converter",
    description: "A web application for converting various cryptocurrencies.",
    icons: ["/html.png", "/css.png", "/react.png", "/tailwind.png"],
    link: true,
  },
  {
    src: "/veterinary.png",
    title: "Veterinary Appointments",
    description: "An app designed to manage veterinary appointments.",
    icons: ["/html.png", "/css.png", "/react.png", "/tailwind.png"],
    link: true,
  },
  {
    src: "/Expense Control.png",
    title: "Expense Control",
    description: "A web-based tool for managing expenses.",
    icons: ["/html.png", "/css.png", "/react.png", "/tailwind.png"],
    link: true,
  },
  {
    src: "/Line Drawing.png",
    title: "Line Drawing",
    description: "An application for creating and editing line drawings.",
    icons: ["/html.png", "/css.png", "/js.png"],
    link: true,
  },
  {
    src: "/pokedex.png",
    title: "Pokedex",
    description: "A digital Pokédex showcasing information about Pokémon.",
    icons: ["/html.png", "/css.png", "/js.png"],
    link: true,
  },
  {
    src: "/twitterClone.png",
    title: "Twitter Clone",
    description: "A simplified version of Twitter, replicating key features.",
    icons: ["/next.png", "/tailwind.png", "/ts.png", "/react.png"],
    link: false,
  },
  {
    src: "/manageBooks.png",
    title: "Manage Books",
    description: "A book management system.",
    icons: ["/html.png", "/css.png", "/node-js.png", "/express.png"],
    link: false,
  },
  {
    src: "/hometask.png",
    title: "Home Task",
    description: "An application designed to organize and manage home tasks.",
    icons: [
      "/html.png",
      "/tailwind.png",
      "/node-js.png",
      "/express.png",
      "/mongodb.png",
      "/react.png",
    ],
    link: false,
  },
  {
    src: "/favoriteVideos.png",
    title: "Favorite Videos",
    description: "A web tool for saving and managing favorite videos.",
    icons: ["/html.png", "/css.png", "/react.png"],
    link: false,
  },
  {
    src: "/americanStore.png",
    title: "American Store",
    description: "An online store prototype for American products.",
    icons: [
      "/html.png",
      "/css.png",
      "/js.png",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/java/java-plain.svg",
      "https://raw.githubusercontent.com/devicons/devicon/55609aa5bd817ff167afce0d965585c92040787a/icons/spring/spring-original.svg",
    ],
    link: true,
  },
];

export default projectsData;
